export const TableData = [
  { customer: "John", month: "January", purchase: 120 },
  { customer: "John", month: "February", purchase: 80 },
  { customer: "John", month: "February", purchase: 80 },
  { customer: "John", month: "February", purchase: 70 },
  { customer: "John", month: "March", purchase: 150 },
  { customer: "Alice", month: "January", purchase: 70 },
  { customer: "Alice", month: "February", purchase: 110 },
  { customer: "Alice", month: "March", purchase: 90 },
  { customer: "Peter", month: "January", purchase: 200 },
  { customer: "Peter", month: "February", purchase: 310 },
  { customer: "Peter", month: "March", purchase: 50 },
  { customer: "Michael", month: "January", purchase: 130 },
  { customer: "Michael", month: "February", purchase: 60 },
  { customer: "Michael", month: "February", purchase: 90 },
  { customer: "Michael", month: "February", purchase: 10 },
  { customer: "Michael", month: "March", purchase: 50 },
  { customer: "Stuart", month: "January", purchase: 80 },
  { customer: "Stuart", month: "February", purchase: 110 },
  { customer: "Stuart", month: "March", purchase: 90 },
  { customer: "Jihon", month: "January", purchase: 100 },
  { customer: "Jihon", month: "February", purchase: 310 },
  { customer: "Jihon", month: "March", purchase: 50 },
];
